language: node_js
node_js:
  - "8"
  - "10"
matrix:
  fast_finish: true
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
    - os: linux
      dist: trusty
    - os: osx
    - os: windows
      before_script:
        - git config core.autocrlf false
        - rm .git/index
        - git reset --hard
cache: npm
install:
  - npm install
script:
  - npm run lint -- --no-fix
  - npm run test:unit
  - npm run build
  - npm run storybook:build -- --quiet
notifications:
  slack: it-slaves:xRVaXMWqCiZPZLOFTiXe8YoY
