language: node_js
node_js:
  - "8"
  - "10"
install: npm install
script:
  - npm run test:unit
  - npm run lint -- --no-fix
  - npm run build
  - npm run storybook:build
notifications:
  slack: it-slaves:xRVaXMWqCiZPZLOFTiXe8YoY
