language: node_js
node_js:
  - "8"
  - "10"
os:
  - linux
  - osx
  # - windows # FIXME: 윈도우 빌드 속도가 개선될 때 다시 추가
cache: npm
install:
  - npm install
before_script:
  - git config core.autocrlf false
  - rm .git/index
  - git reset --hard
script:
  - npm run lint -- --no-fix
  - npm run test:unit
  - npm run build
  - npm run storybook:build -- --quiet
notifications:
  slack: it-slaves:xRVaXMWqCiZPZLOFTiXe8YoY
