language: node_js
node_js:
  - "8"
  - "10"
os:
  - "linux"
  - "osx"
  - "windows"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      git config --global core.autocrlf true;
      git checkout -- .;
    fi
install:
  - npm install
script:
  - npm run test:unit
  - npm run lint -- --no-fix
  - npm run build
  - npm run storybook:build -- --quiet
notifications:
  slack: it-slaves:xRVaXMWqCiZPZLOFTiXe8YoY
